[build]
  publish = "docs/.next"
  command = "cd docs && yarn install && ../scripts/netlify.sh"

[dev]
  targetPort = 3000
  port = 8888
  framework = "#custom"
  autoLaunch = false

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://gestalt.netlify.app/*"
  to = "https://gestalt.pinterest.systems/:splat"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
